import { Inter } from "next/font/google";
import Navbar from "@/components/topNavbar";
import { ThemeProvider } from "@/components/themes-provider";
import LeftNavComp from "@/components/leftNavComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "new web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <html className={inter.className}>
          {/* <Navbar /> */}
          <LeftNavComp />
          {children}
        </html>
      </ThemeProvider>
    </>
  );
}
