import { Inter } from "next/font/google";
import Navbar from "@/components/topNavbar";
import { ThemeProvider } from "@/components/themes-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "new web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </ThemeProvider>
    </>
  );
}
